[package]
name = "eclat-backend-opencl"
version = "0.1.0"
edition = "2024"
description = "OpenCL backend for Eclat"

[dependencies]
eclat = { path = "../.." }
ocl = "0.19"
log = { version = "0.4", features = ["std"] }
ctor = "0.2"
