[package]
name = "harp-nn-derive"
version = "0.1.0"
edition = "2021"
description = "Derive macros for harp-nn crate"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "parsing"] }
quote = "1"
proc-macro2 = "1"
