[package]
name = "harp-nn"
version = "0.1.0"
edition = "2024"
description = "Neural network layers and utilities for Harp"

[dependencies]
harp = { path = "../.." }
harp-nn-derive = { path = "../nn-derive" }
