[package]
name = "harp-autograd"
version = "0.1.0"
edition = "2024"

[features]
default = []
ndarray = ["dep:ndarray"]

[dependencies]
harp = { path = "../.." }
log = "0.4"
ndarray = { version = "0.16", optional = true }

[dev-dependencies]
env_logger = "0.10"
